services:
  openeocraft:
    platform: linux/amd64 # Required for torch - no ARM64 Linux binaries available
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
    container_name: openeocraft
    ports:
      - "8000:8000"
    restart: always
